### ISSUE TITLE
change frida port

### ISSUE THREAD

**Issue by Royalton** [m0bilesecurity/RMS-Runtime-Mobile-Security#124]
**Is your feature request related to a problem? Please describe.**
Currently if you run frida server on the android with a non default port RMS will act as if frida is not running on the phone. using `frida-server -l 0.0.0.0:<port>` you can run frida to run on the device using the non standard port , you can run `frida-ps -U` from the connected computer and get an output. 

**Describe the solution you'd like**
some place to configure the port that frida server is running on

**Comment by m0bilesecurity** [comment]
Added this feature in RMS v1.5.19

Please check:

`Default RMS port has been changed from 5000 to 5491 because since MacOS Ventura, port 5000 is the Control Center's default port. If you wish to change the default port, you can also run RMS with the --port parameter followed by the desired port number e.g. rms --port 9000`
