### ISSUE TITLE
iOS - Static Analysis not working , getting 500 Internal Server Error page

### ISSUE THREAD

**Issue by ganesh2183** [m0bilesecurity/RMS-Runtime-Mobile-Security#43]
I connected to Non Jailbroken device using Frida gadget. I am able to list process/application running in iOS device using **frida-ps -U**

When I try with 'Spawn' getting 500 Internal Server Error page. But it works fine with 'Attach'. Why ??

Also when i click on Static Analysis again getting 500 Internal Server Error page

Please help on this to fix.

**Comment by m0bilesecurity** [comment]
Hey @ganesh2183,
thanks for you interested in RMS.

As explained in issue #42, if FRIDA is running in [**Gadget mode**](https://frida.re/docs/gadget/) **you are not allowed to spawn other processes**.

You are only allowed to **attach** the process where the FRIDA Gadget has been injected (It is usually called "Gadget").

I don't know exactly what you are trying to do because if you are running in Gadget mode, the only process that you are allowed to see should be the one called Gadget.

If your device is not Jailbroken, you are not allowed to run the Static Analysis script or use other useful stuff that RMS performs in background in order to improve the Reverse Engineering experience.

Best
